version: '3'
services:
    prometheus:
      image: prom/prometheus
    registry-service:
      build:
          context: ../../exporter-registry/
      ports:
        - "7249:7249"
    grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      volumes:
        - ./grafana/provisioning:/etc/grafana/provisioning
        - ./grafana/dashboards:/etc/grafana/dashboards


